apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:

  # Capacity
  capacity:
    storage: 5Gi

  # Filesystem - mounts pods to a directory
  # Block 
  volumeMode: Filesystem

  # ReadWriteOnce -- the volume can be mounted as read-write by a single node
  # ReadOnlyMany -- the volume can be mounted read-only by many nodes
  # ReadWriteMany -- the volume can be mounted as read-write by many nodes
  accessModes:
    - ReadWriteOnce

  # Delete - Associated storage can be deleted in case of AWS EBS, GCE PD
  # Retain - Manual reclamation
  # Recycle - basic scrub (rm -rf /thevolume/*)
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: "/data"
