apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
  labels:
    name: pod-with-volume
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: /opt
        name: nginx-vol
  volumes:
    - name: nginx-vol
      awsElasticBlockStore:
        volumeID: "<volume id>"
        fsType: ext4