apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
  labels:
    name: pod-with-volume
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: /opt
        name: host-vol
  volumes:
    - name: host-vol
      hostPath:
        path: /data
        type: Directory