apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%  # how many pods we can add at a time
      maxUnavailable: 25%  # maxUnavailable define how many pods can be unavailable during the rolling update
    type: RollingUpdate 

  # strategy:
  #   type: Recreate

  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
  selector:
    matchLabels:
      name: mysql
  replicas: 2
  volumeClaimTemplates:
    - metadata:
        name: mypvc
      spec:
        resources:
          requests:
            storage: 50Mi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

  