apiVersion: v1
kind: Pod
metadata:
  name: cm-sample-5-pod
spec:
  containers:
    - name: cm-sample-5-ctr
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
          # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: cm-sample-5        # The ConfigMap this value comes from.
              key: player_initial_lives  # The key to fetch.
        - name: UI_PROPERTIES
          valueFrom:
            configMapKeyRef:
              name: cm-sample-5
              key: ui_properties_file_name # This maps to the key in the volume mount
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: cm-sample-5
        # An array of keys from the ConfigMap to create as files
        items:
          - key: "game.properties"
            path: "game.properties"
          - key: "user-interface.properties"
            path: "user-interface.properties"

