apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 8080
      readinessProbe:
        # Specified a delay after which the probe can start
        initialDelaySeconds: 60
        # How often to probe?
        periodSeconds: 5

        # By Default the app stops checking for the probe after 3 attempts, this 
        # value can be modified by the use of failureThreshold
        failureThreshold:  8

        exec:
          command:
            - <command-1>
            - args0
            - args 1