# Refer to readme.md for creation of the ubuntu-sleeper2.0
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu-sleeper-2
    image: ubuntu-sleeper-2
    env:
    - name: password
      valueFrom:
        secretKeyRef: 
          name: my-secret
          key: <some-value>
