# This way is used to mount a config map as a volume.
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu-sleeper-2
    image: ubuntu-sleeper-2
    volumeMounts:
    - mountPath: /etc/config
      name: secret-volume

  # This can be viewed using ls /etc/config/<key>
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret-map
