apiVersion: v1
kind: Secret
metadata:
  name: sample-2-secret
type: Opaque
data:
  DB_HOST: c29tZWhvbWU=
  DB_USER: c29tZXVzZXI=
  DB_PASSWORD: c29tZXBhc3M=

---

apiVersion: v1
kind: Pod
metadata:
  name: sample-2-secret-pod
  labels:
    purpose: demonstrate-secrets
spec:
  containers:
  - name: sample-2-secret-ctr
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: sample-2-secret