apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  serviceAccountName: <specify>
  # in case we decide not to mount a service account automatically.
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
