apiVersion: v1
kind: Pod
metadata:
  name: my-secure-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
    - "sleep"
    - "2000"
    securityContext:
      runAsUser: 1000

      # Capabilities are not supported at POD Level
      capabilities:
        add:
        - MAC_ADMIN
        - SYS_TIME