# This way is used to inject all the values in the config map to the environment variable
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu-sleeper-2
    image: ubuntu-sleeper-2
    envFrom:
    - configMapRef: 
        name: <config-map-name>
