apiVersion: v1
kind: Secret
metadata:
  name: sample-3-secret
type: Opaque
data:
  DB_HOST: c29tZWhvbWU=
  DB_USER: c29tZXVzZXI=
  DB_PASSWORD: c29tZXBhc3M=

---

# Refer to readme.md for creation of the ubuntu-sleeper2.0
apiVersion: v1
kind: Pod
metadata:
  name: sample-3-secret-pod
  labels:
    purpose: demonstrate-secrets
spec:
  containers:
  - name: sample-3-secret-ctr
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /config
      name: secret-volume

  # This can be viewed using ls /etc/config/<key>
  volumes:
    - name: secret-volume
      secret:
        secretName: sample-3-secret
