apiVersion: v1
kind: Pod
metadata:
  name: rm-sample-1-pod
  labels:
    name: rm-sample-1-pod
spec:
  containers:
  - name: rm-sample-1-ctr
    image: alpine
    command: ["sleep", "3600"]
    resources:
      requests:
        #Gibibyte, Mebibyte, Kibibyte
        memory: "128Mi"
        # vcpu - m refers to milli, lowest value is the latest 1m, 0.1=100m
        # 1m = vpcu AWS, 1 Azure Core
        cpu: "500m"
      limits:
        # Default is 512Mi
        memory: "512Mi"
        cpu: "1000m"
