apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: mypod
          image: ubuntu:latest
          command: ['expr','2','+',"3"]
      # Always, OnFailure, and Never      
      # Default is Always
      # In case of a job only OnFailure or Never are allowed.
      restartPolicy: Never
  
  # To do so, set .spec.backoffLimit to specify the number of 
  # retries before considering a Job as failed. The back-off limit is set by default to 6. Failed Pods associated with the Job are recreated by the Job controller with an exponential 
  # back-off delay (10s, 20s, 40s ...) capped at six minutes.       
  backoffLimit: 4      