apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: ubuntu:latest
      command: ['expr','2','+',"3"]
  # Always, OnFailure, and Never      
  # Default is Always
  restartPolicy: Never