apiVersion: v1
kind: Pod
metadata:
  name: sc-sample-3-pod
spec:
  containers:
  - name: sc-sample-3-ctr
    image: alpine
    command: ["sleep", "3600"]
    securityContext:
      # Capabilities are not supported at POD Level
      capabilities:
        add:
        - MAC_ADMIN
        - SYS_TIME