apiVersion: v1
kind: Service
metadata:
  name:
spec:
  type: 
  ports:
  - port:
    nodePort:
    targetPort:
  selector:
    <label>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:
spec:
  resources:
    requests:
      storage:
  volumeMode:
  accessModes:

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:
spec:
  capacity:
    storage:
  volumeMode:
  accessModes:
  -
  persistentVolumeReclaimPolicy: 
  storageClassName:
  hostPath:
    path:

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 
provisioner:
property:
  type:
reclaimPolicy
allowVolumeExpansion:
volumeBindingMode:


---
apiVersion: v1
kind: Pod
metadata:
  name: <name>
  label:
    <key>: <value>
spec:
  containers:
  - name: 
    image: <image-name-in-repo>:<version>
    env:
      - name:
        value: 
      - name:
        valueFrom:
          configKeyMapRef:
            name:
            key:
      - name:
        valueFrom:
          secretKeyMapRef:
            name:
            key:        
    envFrom:
      - secretRef:
          name:
      - configMapRef:
          name:
    resources: # resources requested and limits
      request:
        cpu:
        memory:
      limits:
        cpu:
        memory:
    command: # Dockerfile entry override
      - ""
      - ""
    args: # Dockerfile command override
      - ""
    ports:
    - containerPort: <container-port>
    volumeMounts:
      - name: <same-name-as-volume-mount>
        mountPath: <container-path>
  volumes:
    - name:
      hostPath:
        path: 
        type: 
    - name:
      persistentVolumeClaim:
        claimName: 