apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-sample-3
data:
  APP_COLOR: red
  NAME: Yay!
  AGE: Guess what?

---

# This way is used to inject all the values in the config map to the environment variable
# This methodology is used to inject only a desired Value to the environment variable
apiVersion: v1
kind: Pod
metadata:
  name: cm-sample-3-pod
spec:
  containers:
  - name: cm-sample-3-ctr
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - configMapRef:
        name: cm-sample-3
