apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    serviceAccount: <specify>
    # in case we decide not to mount a service account automatically.
    automountServiceAccountToken: false