apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      name: nginx
