apiVersion: v1
kind: Pod
metadata:
  name: sc-sample-1-pod
spec:
  containers:
  - name: sc-sample-1-ctr
    image: alpine
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1000
      # Capabilities are not supported at POD Level
      capabilities:
        add:
        - MAC_ADMIN
        - SYS_TIME