apiVersion: v1
kind: Pod
metadata:
  name: sample-2-pod-container-running
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do    echo \"hello\";    sleep 2; done" ]