apiVersion: v1
kind: Secret
metadata:
  name: sample-4-secret
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth

apiVersion: v1
kind: Pod
metadata:
  name: sample-4-secret-pod
  labels:
    purpose: demonstrate-secrets
spec:
  containers:
  - name: sample-4-secret-ctr
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /config
      name: secret-volume

  # This can be viewed using ls /etc/config/<key>
  volumes:
    - name: secret-volume
      secret:
        secretName: sample-4-secret