apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: k8-mount
          mountPath: /usr/share/nginx/html
  volumes:
    - name: k8-mount
      hostPath:
        path: /tmp/k8