apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: nginx-mount
          mountPath: /usr/share/nginx/html

  volumes:
  - name: nginx-mount
    persistentVolumeClaim:
      claimName: nginx-pvc