apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 50Mi
  
  volumeMode: Filesystem
  
  accessModes:
  - ReadWriteMany
  
  persistentVolumeReclaimPolicy: Retain
  
  storageClassName: slow

  hostPath: 
    path: /tmp/k8