apiVersion: v1
kind: Secret
metadata:
  name: sample-1-secret
type: Opaque
data:
  DB_HOST: c29tZWhvbWU=
  DB_USER: c29tZXVzZXI=
  DB_PASSWORD: c29tZXBhc3M=

---

# Refer to readme.md for creation of the ubuntu-sleeper2.0
apiVersion: v1
kind: Pod
metadata:
  name: sample-1-secret-pod
  labels:
    purpose: demonstrate-secrets
spec:
  containers:
  - name: sample-1-secret-ctr
    image: alpine
    command: ["sleep", "3600"]
    env:
    - name: HOST
      valueFrom:
        secretKeyRef:
          name: sample-1-secret
          key: DB_HOST
    - name: USER
      valueFrom:
        secretKeyRef:
          name: sample-1-secret
          key: DB_USER
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: sample-1-secret
          key: DB_PASSWORD