apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  schedule: <Cron-expr>
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
            - name: mypod
              image: ubuntu:latest
              command: ['expr','2','+',"3"]
          # Always, OnFailure, and Never      
          # Default is Always
          restartPolicy: Never