apiVersion: v1
kind: Pod
metadata:
  name: cm-sample-4-pod
spec:
  containers:
    - name: cm-sample-4-ctr
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: cm-sample-4

