apiVersion: v1
kind: Pod
metadata:
  name: sample-command-args-pod-demo
  labels:
    purpose: demonstrate-command-args
spec:
  containers:
  - name: sample-command-args-demo-ctr
    image: debian
    command: ["printenv"] # Entry point in Docker
    args: ["HOSTNAME", "KUBERNETES_PORT"] # CMD in docker
  restartPolicy: OnFailure